# Generated by Django 4.1.3 on 2022-12-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='digitalArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=200)),
                ('mouth', models.CharField(max_length=200)),
                ('clothes', models.CharField(max_length=200)),
                ('bg', models.CharField(max_length=200)),
                ('eyes', models.CharField(max_length=200)),
                ('fur', models.CharField(max_length=200)),
            ],
        ),
    ]
